import { z } from "zod";
import { characterDraftSchema, type BrandBible, type ChannelSpec, type CharacterDraft } from "@channelbase/shared";
import type { LLMProvider } from "@channelbase/providers";

const SYSTEM_PROMPT = `You are the Character Engine of an autonomous channel builder, designing recurring characters
for a long-running media franchise. Every field must be specific enough to keep the character
visually and behaviorally consistent across hundreds of future episodes generated by different
image/video models. visualPrompt must fully describe appearance (species/body/face/hair/eyes/
clothing/accessories/color palette) in one dense paragraph suitable as a standing image-generation
reference; negativePrompt must list things that would break consistency (e.g. "no color changes,
no extra limbs, no different outfit"). consistencyRules and doNotChangeRules are short, enforceable
bullet-style statements used by future scene generation to keep the character on-model.`;

const responseSchema = z.object({ characters: z.array(characterDraftSchema) });

export class CharacterEngine {
  constructor(private readonly llm: LLMProvider) {}

  async generate(spec: ChannelSpec, brand: BrandBible): Promise<CharacterDraft[]> {
    if (!spec.productionRules.requiresCharacters && spec.characters.length === 0) return [];

    const seeds = spec.characters.length
      ? spec.characters.map((c) => `- ${c.name} (${c.role}): ${c.shortDescription}`).join("\n")
      : "No specific characters were requested — invent 1-2 characters appropriate to this channel concept if it would benefit from recurring hosts/mascots, otherwise return an empty array.";

    const prompt = `Channel: ${spec.identity.channelName}, niche: ${spec.identity.niche}
Audience: ages ${spec.audience.targetAgeMin}-${spec.audience.targetAgeMax}
Visual style: ${brand.style.illustrationStyle}, colors: ${brand.style.primaryColors.join(", ")}
Character seeds:
${seeds}

Fully develop each character with appearance, personality, speech style, catchphrases, and a
production-ready visualPrompt/negativePrompt/consistencyRules/doNotChangeRules.`;

    const { characters } = await this.llm.generateStructured({
      systemPrompt: SYSTEM_PROMPT,
      prompt,
      schema: responseSchema,
      maxTokens: 4096,
    });
    return characters;
  }
}
